#!/usr/bin/env bash
# Split /etc/labops/labops.env into gateway / agent / model-proxy environments per
# docs/phase2/02-secret-separation.md. Idempotent, reversible, and never prints a value.
#
#   split-secrets.sh            # split (keeps labops.env as the rollback source)
#   split-secrets.sh --revert   # restore the single-file layout
set -euo pipefail

SRC=/etc/labops/labops.env
GW=/etc/labops/gateway.env
AG=/etc/labops/agent.env
MP=/etc/labops/model-proxy.env
BK=/etc/labops/backups
DROPIN=/etc/systemd/system/labops-gateway.service.d/20-env.conf

# Keys the agent control plane may see. Everything else stays with the gateway.
AGENT_KEYS='SESSION_API_KEY|OH_SECRET_KEY|OH_TELEMETRY_EXPORTER|DO_NOT_TRACK|LABOPS_LLM_MODEL|LABOPS_LLM_FALLBACK_MODEL|LABOPS_LLM_PROVIDER|LABOPS_LLM_REQUEST_TIMEOUT_S|LABOPS_LLM_MAX_RETRIES'
# Keys only the model proxy may see.
PROXY_KEYS='LABOPS_LLM_API_KEY|LABOPS_MODEL_PROXY_TOKEN'

if [ "${1:-}" = "--revert" ]; then
  sudo -n rm -f "$DROPIN"
  sudo -n systemctl daemon-reload
  sudo -n systemctl restart labops-gateway
  echo "reverted: labops-gateway reads $SRC again (agent/proxy env files left in place)"
  exit 0
fi

[ -r "$SRC" ] || { echo "$SRC not readable — run with sudo" >&2; exit 66; }
sudo -n install -d -m 0700 -o root -g root "$BK"
sudo -n install -m 0600 -o root -g root "$SRC" "$BK/labops.env.$(date +%Y%m%d%H%M%S)"

umask 027
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

# --- gateway: everything except the agent-only and proxy-only keys ------------------
{
  echo "# LabOps gateway environment. Generated by scripts/split-secrets.sh."
  echo "# Read only by the labops-gateway unit. Never mounted into a container."
  sudo -n grep -vE "^($AGENT_KEYS|$PROXY_KEYS)=" "$SRC"
  echo "LABOPS_CANARY_GATEWAY=labops-canary-gateway-$(openssl rand -hex 12)"
  echo "LABOPS_MODEL_NET=compose_labops-model"
  echo "LABOPS_MODEL_PROXY=172.31.241.2:8081"
} > "$tmp/gateway.env"

# --- agent: the minimum for model-provider communication and isolated runtime -------
{
  echo "# LabOps agent/investigation environment. Generated by scripts/split-secrets.sh."
  echo "# Supplied to per-investigation containers. Contains NO integration credential:"
  echo "# no Supabase, AWX, Wiki.js, GitHub, SMTP or provider key. The provider key lives"
  echo "# only in $MP; the agent authenticates to the proxy with a per-run token."
  sudo -n grep -E "^($AGENT_KEYS)=" "$SRC" || true
  echo "LABOPS_CANARY_AGENT=labops-canary-agent-$(openssl rand -hex 12)"
} > "$tmp/agent.env"

# --- model proxy: the provider key and the per-run proxy token ----------------------
if sudo -n test -r "$MP"; then
  cp /dev/null "$tmp/model-proxy.env"   # already provisioned; leave it alone
else
  {
    echo "# LabOps model proxy environment. Generated by scripts/split-secrets.sh."
    echo "# The only place LABOPS_LLM_API_KEY exists on this host."
    sudo -n grep -E "^(LABOPS_LLM_API_KEY)=" "$SRC" || echo "LABOPS_LLM_API_KEY=REPLACE_ON_HOST_ONLY"
    echo "LABOPS_MODEL_PROXY_TOKEN=$(openssl rand -hex 24)"
  } > "$tmp/model-proxy.env"
fi

sudo -n install -m 0640 -o root -g labops-gateway "$tmp/gateway.env" "$GW"
sudo -n install -m 0640 -o root -g root           "$tmp/agent.env"   "$AG"
[ -s "$tmp/model-proxy.env" ] && sudo -n install -m 0640 -o root -g root "$tmp/model-proxy.env" "$MP"

# The gateway must read gateway.env only; labops.env stays as the documented rollback path.
sudo -n install -d -m 0755 /etc/systemd/system/labops-gateway.service.d
sudo -n tee "$DROPIN" >/dev/null <<UNIT
[Service]
EnvironmentFile=
EnvironmentFile=$GW
UNIT
sudo -n chmod 0600 "$SRC"
sudo -n systemctl daemon-reload
sudo -n systemctl restart labops-gateway

echo "gateway.env / agent.env / model-proxy.env written; gateway restarted"
echo "next: docker compose up -d model-proxy, then scripts/test-secret-isolation.sh <run_id>"
